### ISSUE TITLE
DocC launch checklist

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#1758]
- [x] announcement blog post
- [x] remove prod feature flag
- [x] TCA docsets backfill (deferred until they come back to us)
- [x] check links of known existing docs in prod
- [x] update SemanticVersion docs
- [x] set up Cloudflare cache

**Comment by finestructure** [comment]
It does, but I haven’t heard back from them how far back they need them. I think unless they’re actually planning to link to these revisions from their README and/or switch over to our docs entirely we can probably drop that from the launch list.
