### ISSUE TITLE
Builder stage

### ISSUE THREAD

**Issue by finestructure** [SwiftPackageIndex/SwiftPackageIndex-Server#561]
# Build trigger mechanism

First take:
1. trigger new releases as part of analysis, where we identify new releases
2. also identify outdated default branches as part of analysis

The problem with this is the following: we can't simply trigger those builds and move on, because we need to check the queue depth on Gitlab before sending or the jobs will error out when the queue is too deep.
So at best we could record those jobs in an intermediate buffer to be triggered as the queue allows. Essentially a queue in front of a queue, which is redundant.

## Builder stage
Instead, what we should do is add a new `Builder` stage to our processing pipeline, with its own candidate selection.
This candidate selection would look as follows:
- any version without builds is eligible
- order by least recently updated/created
- ensure we perhaps have a fast-track mechanism like we do for new packages

A very nice aspect of this candidate selection is its simplicity: just any version without builds. The reason it works is the following:

- new versions automatically fulfill the criterion - they have no versions

But also, a revision change on the default branch is picked up

- when a revision changes on a default branch, version reconciliation sees that and removes the outdated version record and adds a new one. This then _also_ creates a new version without any builds.

## Open questions
- Does this stage get its own stage state?
  → No, that would be mixing concerns
- How does that interact with the current stages, in particular the analysis stage? Presumably, this would interfere with its own candidate selection. So it would probably need to pick up from build _and_ analysis stages
  → That’s the main reason we better not create a new stage
- Think through how to record in progress builds. I.e. say we’ve started processing builds for a version. Once the first builds report back it is not eligible anymore as a whole - which is good. However, we also need to guard against another trigger pass triggering the builds again, because none of the builds has reported a result back yet. Dave’s suggestion to record a record in `builds` indicating the a build is enqueued seems like the way to go.
  → Let’s create build “stubs” with status `enqueued` when builds are triggered. They’ll be updated when the build completes and we should regard `enqueued` builds beyond a certain age as failed and remove them.

## Tasks
- [x] think through implications of an additional stage for candidate selection in other stages
- [x] review/add test for default branch version renewal to ensure revision changes reset the builds
- [x] add `Builder` stage
  - [x] mark significant versions #574 
  - [x] candidate selection
    - [x] include as candidates `enqueued` builds that are more than 6/12/24 (?) hours old (unreported failed builds)
→ clean them up as part of #582 
  - [x] command
  - [x] Gitlab queue depth check
  - [x] env variable to control queue limit
  - [x] switch off override env variable
  - [x] add trigger
    - [x] create `enqueued` build stubs

**Comment by finestructure** [comment]
Supercedes #533 and #534

**Comment by finestructure** [comment]
This actually demonstrates how we’re already invalidating builds: Alamofire had changes pushed to `master` since we’ve run our build and so the newly reconciled version that is attached to that revision doesn’t have builds anymore (we used to show this as one row where `5.2.2` and `master` had identical results):

<img width="611" alt="Screenshot 2020-07-29 at 16 55 04" src="https://user-images.githubusercontent.com/65520/88816291-872ab000-d1bc-11ea-84fb-5022af6eee2a.png">

**Comment by finestructure** [comment]
One problem is that “versions without builds” only triggers when there are no builds at all. What if we add a new Swift version? A new platform? These would only be added for new versions, i.e. new releases or revisions on the default branch.

This may be desirable. However, it won’t deal with cases where builds are only partially completed for a version due to service disruption. Unless we automatically identify this and re-run (perhaps by removing the builds for the partial version) the gaps would remain indefinitely.

The alternative is that we compare all builds attached to a version against the current set of swift versions and platforms we build for. Essentially do a build level reconciliation, adding new builds where there are gaps. And also perhaps pruning builds that aren't reachable via the UI anyway (historic releases, older default branch revisions).

**Comment by finestructure** [comment]
Now that the significant version markers are in place, I’ve come up with the following query for candidate selection:

```sql
-- select versions that don't have a full set of builds
select v.package_id, v.package_name, v.latest, min(v.updated_at) updated_at, count(*)
from versions v
left join builds b on b.version_id = v.id
where v.latest is not null
group by v.package_id, v.package_name, v.latest
having count(*) != 25
order by updated_at, package_id
```

The number 25 will be a computed value from the number of swift versions (5: 4.2, 5.0, 5.1, 5.2, 5.3) times the number of platforms (5: ios, macos-spm, macos-xcode, tvos, watchos).

This candidate list will be the input to the build reconciliation. I.e. for each package we’ll determine which builds are actually missing and trigger those.

**Comment by daveverwer** [comment]
I think this will work, and I think it scales to our next plans (ARM builds, but only on 5.3 and above) as we just add 2 to the count at that point macOS Xcode 5.3 ARM and macOS SPM 5.3 ARM.

I do worry just a little bit that if there's a bug, we may miss it. If instead, we were to bring all records and their associated (or lack of associated) builds back we could go through them in code and not only know which ones were missing but verify that we have correct builds. As I'm typing it, it feels like this is overkill, but relying on a count makes me 😅 a little. It's probably not worth it, but I thought I'd mention it.

**Comment by finestructure** [comment]
Just to record what we discussed this morning (and what’s implemented now): this query is just a preselection step to identify packages that need build reconciliation. If we didn’t do that, we’d churn all 6400 versions with latest != null on every cycle. Especially once we’re done with the first pass, that’d be a lot of unnecessary churn.

One thing to be mindful of is that additions to platforms and swift versions are safe, as they’ll naturally raise the limit. If we remove a platform or, more likely, a swift verions, we must also remove its builds so we don’t inflate the build count with now invalid builds.

**Comment by finestructure** [comment]
Hah, lucky me, the very first package I triggered with the new process was a 404: https://github.com/ole/PropertyWrappers

All builds are correctly pending, because we [error out](https://gitlab.com/finestructure/swiftpackageindex-builder/-/jobs/670084762):

```
$ ./build.sh
Error: ShellOut encountered an error
Status code: 128
Message: "fatal: could not read Username for 'https://github.com': Device not configured"
Output: ""
Clone URL: https://github.com/ole/PropertyWrappers.git
Reference: master
ERROR: Job failed: exit status 1
```

<img width="1210" alt="Screenshot 2020-08-04 at 13 20 34" src="https://user-images.githubusercontent.com/65520/89288213-8f1f9f80-d655-11ea-8a71-a31ccf6373d5.png">

(We should bubble that up as an actual build error though)

**Comment by finestructure** [comment]
Another 404, https://github.com/hyperhooks/core. I don’t think this is chance then. It’s picking up oldest packages first and that may bring to the front packages we can’t update, because they’re unavailable.

**Comment by finestructure** [comment]
Next up:

- https://github.com/hyperhooks/hyperswift.git

But then a working url:

<img width="1210" alt="Screenshot 2020-08-04 at 13 30 42" src="https://user-images.githubusercontent.com/65520/89288950-bd51af00-d656-11ea-8eb6-6d3f6684fa1d.png">

**Comment by finestructure** [comment]
Working beautifully :)

**Comment by finestructure** [comment]
The way to run the command manually is

```
ssh spi-dev
# attach to one of the containers, for instance the analyser
docker exec -it spi_analyze_1 bash
# then inside the container run the command we will later run via docker-compose
root@6bbeb922eb4e:/run# ./Run trigger-builds --limit 1
Triggering builds (limit: 1) …
```

I’ll add an issue to provide more feedback about what package id is being triggered.

**Comment by finestructure** [comment]
<img width="899" alt="Screenshot 2020-08-05 at 13 56 17" src="https://user-images.githubusercontent.com/65520/89410119-72519d80-d723-11ea-986f-67e3b4bb1ddf.png">

**Comment by finestructure** [comment]
![builds](https://user-images.githubusercontent.com/65520/89411473-c493be00-d725-11ea-8e98-91dc0483592d.gif)
